### ISSUE TITLE
Support DOIT DEVKIT V1 board

### ISSUE THREAD

**Issue by Sjors** [fonske/Brink-flair-modbus#5]
I bought one of these:
https://docs.platformio.org/en/latest/boards/espressif32/esp32doit-devkit-v1.html

I was able to get it work with:

```yaml
esp32:
  board: esp32doit-devkit-v1

uart:
  tx_pin: 1
  rx_pin: 3

logging:
  baud_rate: 0
```

I'm happy to make a pull request to add this, but I don't know how one goes about supporting multiple ESP32 boards.

You may also want to clarify that UART0 is expected (UART2 does nothing for me).
